// players
globalvar PLAYER1, PLAYER2;
PLAYER1 = 0
PLAYER2 = 1

// server state
globalvar DISCONNECTED, BROADCASTING, CONNECTED;
DISCONNECTED = 0
BROADCASTING = 1
CONNECTED = 2

// packet types to client
// ** THESE MUST BE SAME VALUES ON CLIENT SIDE
globalvar OBJ_CREATE, OBJ_CREATE_SPEED_DIR, OBJ_POS, OBJ_DESTROY, SOUND_PLAY, EFFECT_CREATE;
OBJ_CREATE = 0
OBJ_CREATE_SPEED_DIR = 1
OBJ_POS = 2
OBJ_DESTROY = 3
SOUND_PLAY = 4
EFFECT_CREATE = 5

// packet types from client
globalvar INPUT;
INPUT = 0

// object types
globalvar OBSTACLE, FLAG, BULLET;
OBSTACLE = 0
FLAG = 1
BULLET = 2
